version: '3.1'

volumes:
  bookstore_db:

services:
  app-serve:
    build: .
    image: myapp
    volumes:
      - bookstore_db:/app/bookstore_db
    command: npm run serve:production
    ports:
      - 8080:5000
    expose:
      - 4200
    environment:
      - PYTHONUNBUFFERED=1

  app-e2e-tests:
    image: myapp
    command: dockerize -wait tcp://app-serve:4200
      -wait tcp://selenium-chrome-standalone:4444
      -timeout 10s -wait-retry-interval 1s bash -c "npm run e2e"
    depends_on:
      - app-serve
      - selenium-chrome-standalone

  selenium-chrome-standalone:
    image: selenium/standalone-chrome
    expose:
      - 44444
