name: Acceptance Stage

on:
  workflow_run:
    workflows: ['Commit Stage']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
#    container:
#      image: 'davef77/davesbookstore'
#    env:
#      NODE_ENV: test
#      SELENIUM_HUB_HOST: hub
#      TEST_HOST: testHost:5000

    services:
      selenium:
        image: selenium/standalone-chrome
#      hub:
#        image: selenium/hub:3.141.59-gold
#      firefox:
#        image: selenium/node-firefox:3.141.59-gold
#        env:
#          HUB_HOST: hub
#          HUB_PORT: 4444

      bookstore:
        image: 'davef77/davesbookstore'

    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Acceptance Tests
        run: python -m pytest tests/acceptance
