name: Acceptance Stage

on:
  workflow_run:
    workflows: ['Commit Stage']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      bookstore:
        image: 'davef77/davesbookstore:1.0'
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Acceptance Tests
        run: python -m pytest tests/acceptance
        env:
          BOOKSTORE_HOST: localhost
          BOOKSTORE_PORT: 5000


