name: Acceptance Stage

on:
  workflow_run:
    workflows: ['Commit Stage']
    types:
      - completed

jobs:
  start_release_candidate:
    runs-on: ubuntu-latest
    services:
      bookstore:
        image: 'davef77/davesbookstore'
        ports:
          - 5000:5000

    steps:
    - name: Confirm RC Ready
      run: http://localhost:5000

  acceptance_test:
    needs: start_release_candidate
    runs-on: ubuntu-latest

    steps:
    - name: Acceptance Test with pytest
      run: |
       python -m pytest tests/acceptance
